# Generated by Django 4.1 on 2022-08-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userwithphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='userph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.userwithphoto'),
        ),
    ]
