# Generated by Django 4.1 on 2022-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_message_userph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
