# Generated by Django 4.1 on 2022-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userwithphoto_address_userwithphoto_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithphoto',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='images'),
        ),
    ]
