# Generated by Django 4.1 on 2022-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_userwithphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='dis',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
